plugins {
    id 'org.springframework.boot' version '3.2.2' apply false
    id 'io.spring.dependency-management' version '1.1.4' apply false
}

allprojects {
    repositories {
        mavenCentral()
    }
}

subprojects { subproject ->
    if (subproject.buildFile.exists() &&
            subproject.name != 'domain' &&
            subproject.name != 'infraestructure' &&
            subproject.name != 'applications' &&
            subproject.name != 'drivenadapters' &&
            subproject.name != 'entrypoints') {

        group = 'com.nequi'
        version = '0.0.1-SNAPSHOT'
    }
}