spring:
  application:
    name: wallet-pocket
  r2dbc:
    url: ${DATABASE_URL}?sslMode=require
    username: wallet_admin
    password: ${DATABASE_PASSWORD}
  sql:
    init:
      mode: never

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST:localhost}
    port: ${SPRING_RABBITMQ_PORT:5672}
    username: ${SPRING_RABBITMQ_USERNAME:guest}
    password: ${SPRING_RABBITMQ_PASSWORD:guest}